// components/tilted-panel.tsx
'use client'

import type { ReactNode } from 'react'
import { cn } from '@/lib/utils'

/**
 * A side panel tilted inward around its vertical hinge (the outer screen
 * edge), as if the whole surface leans toward the viewer/center — like the
 * inner walls of the deep well continuing outward.
 */
export function TiltedPanel({
  side,
  children,
  className,
}: {
  side: 'left' | 'right'
  children: ReactNode
  className?: string
}) {
  return (
    <div
      className="hidden shrink-0 md:flex md:items-center md:justify-center"
      style={{ perspective: '1600px', width: 'clamp(200px, 17vw, 260px)' }}
    >
      <div
        className={cn(
          'h-[88%] border border-border bg-card/80 shadow-2xl shadow-black/10 backdrop-blur-xl',
          side === 'left' ? 'rounded-r-2xl border-l-0' : 'rounded-l-2xl border-r-0',
          className,
        )}
        style={{
          transform: side === 'left' ? 'rotateY(14deg)' : 'rotateY(-14deg)',
          transformOrigin: side === 'left' ? 'left center' : 'right center',
        }}
      >
        {children}
      </div>
    </div>
  )
}

// vue-app/src/components/TiltedPanel.vue
<script setup lang="ts">
// A side panel tilted inward around its vertical hinge (the outer screen
// edge), as if the whole surface leans toward the viewer/center — like the
// inner walls of the deep well continuing outward.
const { side } = defineProps<{ side: 'left' | 'right' }>()
</script>

<template>
  <div
    class="hidden shrink-0 md:flex md:items-center md:justify-center"
    style="perspective: 1600px; width: clamp(248px, 21vw, 372px)"
  >
    <div
      class="h-[88%] border border-border bg-card/80 shadow-2xl shadow-black/10 backdrop-blur-xl"
      :class="side === 'left' ? 'rounded-r-2xl border-l-0' : 'rounded-l-2xl border-r-0'"
      :style="{
        transform: side === 'left' ? 'rotateY(14deg)' : 'rotateY(-14deg)',
        transformOrigin: side === 'left' ? 'left center' : 'right center',
      }"
    >
      <slot />
    </div>
  </div>
</template>
